{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.1678.0 (24.12)+2a034ab280bddf891eb7bb9ebfe6996f9c3a3196"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"D_Customers\",\"D_Suppliers\",\"D_Shipments\",\"D_Products\",\"D_Orders\",\"F_Order_Items\",\"F_OrderData\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBI_RemovedChildren",
        "value": "[{\"remoteItemId\":{\"foreignKeyRelationship\":{\"fromTableLocalLineageTag\":\"d93ab93f-9723-4988-a153-2e4f8b8402e9\",\"fromColumnLocalLineageTag\":\"3c535b96-a484-407b-9883-81a6dee51e00\",\"toTableLocalLineageTag\":\"fa2d46b5-bc26-4ca1-b90b-87712ff52cb3\",\"toColumnLocalLineageTag\":\"deae584f-f764-4123-95ed-b65d2071b826\"}},\"objectType\":\"Relationship\"}]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "F_Order_Items",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = PostgreSQL.Database(\"localhost\", \"SQL_projekti\"),",
          "    public_Order_Items = Source{[Schema=\"public\",Item=\"Order_Items\"]}[Data],",
          "    #\"Removed Columns\" = Table.RemoveColumns(public_Order_Items,{\"public.Orders\", \"public.Products\"})",
          "in",
          "    #\"Removed Columns\""
        ],
        "kind": "m",
        "lineageTag": "c3be3b4f-c33e-4d69-8d46-47d02719d28a"
      },
      {
        "name": "D_Shipments",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = PostgreSQL.Database(\"localhost\", \"SQL_projekti\"),",
          "    public_Shipments = Source{[Schema=\"public\",Item=\"Shipments\"]}[Data],",
          "    #\"Removed Columns\" = Table.RemoveColumns(public_Shipments,{\"public.Orders\"})",
          "in",
          "    #\"Removed Columns\""
        ],
        "kind": "m",
        "lineageTag": "3d7fce45-1431-4fd5-8d0b-a1d46302dcc2"
      },
      {
        "name": "D_Orders",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = PostgreSQL.Database(\"localhost\", \"SQL_projekti\"),",
          "    public_Orders = Source{[Schema=\"public\",Item=\"Orders\"]}[Data],",
          "    #\"Removed Columns\" = Table.RemoveColumns(public_Orders,{\"public.Customers\", \"public.Order_Items\", \"public.Shipments\"}),",
          "    #\"Merged Queries\" = Table.NestedJoin(#\"Removed Columns\", {\"order_id\"}, D_Shipments, {\"order_id\"}, \"D_Shipments\", JoinKind.LeftOuter),",
          "    #\"Expanded D_Shipments\" = Table.ExpandTableColumn(#\"Merged Queries\", \"D_Shipments\", {\"shipment_id\", \"shipped_date\", \"delivery_date\", \"shipping_cost\"}, {\"shipment_id\", \"shipped_date\", \"delivery_date\", \"shipping_cost\"})",
          "in",
          "    #\"Expanded D_Shipments\""
        ],
        "kind": "m",
        "lineageTag": "b47d4393-3da2-4f9d-99a8-6d3a2118419f"
      }
    ],
    "extendedProperties": [
      {
        "name": "SQLBI_BRAVO_ManageDatesConfiguration",
        "type": "json",
        "value": {
          "name": "Config-01",
          "autoNaming": 1,
          "autoScan": 127,
          "dateAvailable": true,
          "dateEnabled": true,
          "dateReferenceTableName": "DateAutoTemplate",
          "dateReferenceTableValidation": 2,
          "dateTableName": "D_Date",
          "dateTableValidation": 2,
          "defaults": {
            "firstDayOfWeek": 1
          },
          "description": "Standard gregorian calendar",
          "exceptTablesColumns": [],
          "holidaysAvailable": true,
          "holidaysDefinitionTableName": "HolidaysDefinition",
          "holidaysDefinitionTableValidation": 0,
          "holidaysEnabled": false,
          "holidaysTableName": "Holidays",
          "holidaysTableValidation": 0,
          "isCurrent": false,
          "isCustom": false,
          "isoCountry": "US",
          "onlyTablesColumns": [],
          "targetMeasures": [],
          "templateUri": "file:///C:/Users/Tony/AppData/Local/Bravo/.temp/ManageDates/Templates/Config-01.template.json",
          "timeIntelligenceAvailable": true,
          "timeIntelligenceEnabled": true
        }
      }
    ],
    "relationships": [
      {
        "name": "d00424f0-5f7f-4d39-813f-226076ee7edb",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "product_id",
        "fromTable": "F_OrderData",
        "toColumn": "product_id",
        "toTable": "D_Products"
      },
      {
        "name": "c4496795-1bf6-4469-5d7a-3d8375672871",
        "fromColumn": "customer_id",
        "fromTable": "F_OrderData",
        "toColumn": "customer_id",
        "toTable": "D_Customers"
      },
      {
        "name": "2efb2446-b977-47a6-593d-48f6ddd69e49",
        "fromColumn": "supplier_id",
        "fromTable": "F_OrderData",
        "toColumn": "supplier_id",
        "toTable": "D_Suppliers"
      },
      {
        "name": "41ed0b0f-09cd-cd89-e91d-28b50408233f",
        "fromColumn": "delivery_date",
        "fromTable": "F_OrderData",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "D_Date"
      },
      {
        "name": "6c121a56-98b1-37af-dbec-df9cc121245f",
        "fromColumn": "order_date",
        "fromTable": "F_OrderData",
        "toColumn": "Date",
        "toTable": "D_Date"
      },
      {
        "name": "abdaf241-f957-05fe-8afc-22574d279244",
        "fromColumn": "shipped_date",
        "fromTable": "F_OrderData",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "D_Date"
      }
    ],
    "sourceQueryCulture": "fi-FI",
    "tables": [
      {
        "name": "D_Customers",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d034873b-26a9-465c-98a4-97ceee98858c",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b044205c-47e4-4797-a2c0-29bad2fd8c20",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb2fdfbb-547b-4f76-bc3a-4c3642c2f78f",
            "sourceColumn": "location",
            "summarizeBy": "none"
          },
          {
            "name": "email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b71e248-22af-4bb0-bb9e-817af6642c85",
            "sourceColumn": "email",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3f34b21f-caa6-43aa-b4a6-2a6ad3b69d19",
        "partitions": [
          {
            "name": "D_Customers",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"localhost\", \"SQL_projekti\"),",
                "    public_Customers = Source{[Schema=\"public\",Item=\"Customers\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(public_Customers,{\"public.Orders\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "D_Suppliers",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "supplier_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "deae584f-f764-4123-95ed-b65d2071b826",
            "sourceColumn": "supplier_id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b787aa6-bf6d-4887-83d7-889f9fdfc2b8",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "contact_info",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aaf0a3a4-6489-433b-a37d-a589f20acbc6",
            "sourceColumn": "contact_info",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43c87d7d-b9dd-4e49-a45b-76e30a18d90b",
            "sourceColumn": "country",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fa2d46b5-bc26-4ca1-b90b-87712ff52cb3",
        "partitions": [
          {
            "name": "D_Suppliers",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"localhost\", \"SQL_projekti\"),",
                "    public_Suppliers = Source{[Schema=\"public\",Item=\"Suppliers\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(public_Suppliers,{\"public.Products\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "D_Products",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "198c654c-cf2d-4f55-ba84-079c431b1874",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74ffce4a-6656-476f-bfe2-0b981819d441",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7a7c4f0-8e1e-4e18-b4d2-62aff5d63a56",
            "sourceColumn": "category",
            "summarizeBy": "none"
          },
          {
            "name": "price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a7abb64a-98ee-427b-82d8-2f81ea40b5fd",
            "sourceColumn": "price",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3c535b96-a484-407b-9883-81a6dee51e00",
            "sourceColumn": "supplier_id",
            "summarizeBy": "none"
          },
          {
            "name": "stock_quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6953503f-c3fc-4e37-89c1-c90f2b94e421",
            "sourceColumn": "stock_quantity",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d93ab93f-9723-4988-a153-2e4f8b8402e9",
        "partitions": [
          {
            "name": "D_Products",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"localhost\", \"SQL_projekti\"),",
                "    public_Products = Source{[Schema=\"public\",Item=\"Products\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(public_Products,{\"public.Order_Items\", \"public.Suppliers\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Mittarit",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f3ce9c29ef874373bc241e8e334b3ea8"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d6aa1865-431e-4ac0-9039-00dcf6284417",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "100b8e26-e3d0-4e17-830f-639d40d00e08",
        "measures": [
          {
            "name": "Orders Total",
            "expression": "DISTINCTCOUNT('F_OrderData'[order_id])",
            "formatString": "0",
            "lineageTag": "c6eb4578-2d71-4665-bec5-20080bc5388a"
          },
          {
            "name": "Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('F_OrderData'[price_at_purchase])",
            "lineageTag": "52ade0ae-70b0-46bb-850b-733de4e02ab9"
          },
          {
            "name": "Products with low stock",
            "expression": [
              "CALCULATE(",
              "DISTINCTCOUNT('D_Products'[product_id]), FILTER(ALL('D_Products'), 'D_Products'[stock_quantity] < 10))"
            ],
            "formatString": "0",
            "lineageTag": "43d1fb74-6c39-48df-8929-1834e18e7d24"
          },
          {
            "name": "Products high on stock",
            "expression": [
              "CALCULATE(",
              "DISTINCTCOUNT('D_Products'[product_id]), FILTER(ALL('D_Products'), 'D_Products'[stock_quantity] >= 10))"
            ],
            "formatString": "0",
            "lineageTag": "dc264ba8-042f-4dfc-b342-0c8eeaa9b3a6"
          },
          {
            "name": "YTD Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Orders Total",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Orders Total],",
              "        DATESYTD ( 'D_Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "0fbe73a1-43eb-43e9-b5f4-122e3085ea33"
          },
          {
            "name": "QTD Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Orders Total",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Orders Total],",
              "        DATESQTD ( 'D_Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "0ad22e0f-bf3f-45e4-b4aa-1bde98119451"
          },
          {
            "name": "MTD Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Orders Total",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Orders Total],",
              "        DATESMTD ( 'D_Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5c7ab31a-86af-4a68-9727-7607a75ea223"
          },
          {
            "name": "PY Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Orders Total",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Orders Total],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, YEAR ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "bd8e5e70-7082-4180-9a3e-4e92e27e00dc"
          },
          {
            "name": "YOY Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Orders Total",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Orders Total]",
              "VAR __ValuePreviousPeriod = [PY Orders Total]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "5f845d72-3faf-445a-8fbb-e76bdc52935d"
          },
          {
            "name": "YOY % Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Orders Total",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY Orders Total],",
              "    [PY Orders Total]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "6be6bc6a-f225-4d89-8fa9-a1a37c5366a3"
          },
          {
            "name": "PQ Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Orders Total",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Orders Total],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, QUARTER ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "e3417e02-0c38-4f0b-bd61-1c001dc70d51"
          },
          {
            "name": "QOQ Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Orders Total",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Orders Total]",
              "VAR __ValuePreviousPeriod = [PQ Orders Total]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "496a254e-2b22-4e45-a0b0-21085a0ad932"
          },
          {
            "name": "QOQ % Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Orders Total",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ Orders Total],",
              "    [PQ Orders Total]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "ea0fe666-f392-42c0-90e4-96be7a4cd5ac"
          },
          {
            "name": "PM Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Orders Total",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Orders Total],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, MONTH ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "426da027-5e46-4ad2-b649-62772b47963c"
          },
          {
            "name": "MOM Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Orders Total",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Orders Total]",
              "VAR __ValuePreviousPeriod = [PM Orders Total]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "9105836c-ca34-4ef2-aa28-c180d226e66d"
          },
          {
            "name": "MOM % Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Orders Total",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM Orders Total],",
              "    [PM Orders Total]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "358f1054-9ccd-40e0-bf34-d14d6b0e6e45"
          },
          {
            "name": "PYTD Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Orders Total",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD Orders Total],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, YEAR ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "0e2737e4-0329-4066-95d8-c87513f9dc85"
          },
          {
            "name": "YOYTD Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Orders Total",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD Orders Total]",
              "VAR __ValuePreviousPeriod = [PYTD Orders Total]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "d0edf878-32f3-4afd-a7dd-73e03cbf07ad"
          },
          {
            "name": "YOYTD % Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Orders Total",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD Orders Total],",
              "    [PYTD Orders Total]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "a88f9b80-257c-465f-90e4-6fa79724820a"
          },
          {
            "name": "PQTD Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Orders Total",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD Orders Total],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, QUARTER ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ed0f1b2b-3347-44d5-b520-bda6a5f0f268"
          },
          {
            "name": "QOQTD Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Orders Total",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD Orders Total]",
              "VAR __ValuePreviousPeriod = [PQTD Orders Total]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "e4a6c954-735e-45de-8df6-0cdbec137df9"
          },
          {
            "name": "QOQTD % Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Orders Total",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD Orders Total],",
              "    [PQTD Orders Total]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "d433da6b-a639-430f-bf8c-7c26370795d9"
          },
          {
            "name": "PMTD Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Orders Total",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD Orders Total],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, MONTH ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1930bd66-54d6-44a7-9120-21fc4cabbc06"
          },
          {
            "name": "MOMTD Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Orders Total",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD Orders Total]",
              "VAR __ValuePreviousPeriod = [PMTD Orders Total]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "4eeeb2f1-7a9d-4f96-a804-6e85d4dc5d24"
          },
          {
            "name": "MOMTD % Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Orders Total",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD Orders Total],",
              "    [PMTD Orders Total]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "84a85e0d-3b67-4fff-b416-dce9d24c5185"
          },
          {
            "name": "PYC Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Orders Total",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Orders Total],",
              "        PARALLELPERIOD ( 'D_Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6360acc4-5642-4a2d-8223-dd64f3e056ee"
          },
          {
            "name": "YTDOPY Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Orders Total",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD Orders Total]",
              "VAR __ValuePreviousPeriod = [PYC Orders Total]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "01be68ea-8722-4d8d-8ed3-b3a42b4bdb3d"
          },
          {
            "name": "YDTOPY % Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Orders Total",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY Orders Total],",
              "    [PYC Orders Total]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "b82e406e-5c0d-4909-87e8-f59daa65b3e8"
          },
          {
            "name": "PQC Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Orders Total",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Orders Total],",
              "        PARALLELPERIOD ( 'D_Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "dbb903bf-68f3-449f-92f1-56119dea9863"
          },
          {
            "name": "QTDOPQ Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Orders Total",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD Orders Total]",
              "VAR __ValuePreviousPeriod = [PQC Orders Total]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "14df3cc1-6983-4c42-b18a-be8f14d9d323"
          },
          {
            "name": "QDTOPQ % Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Orders Total",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ Orders Total],",
              "    [PQC Orders Total]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "b73afca9-253d-4bb8-aaea-36ff677f4d58"
          },
          {
            "name": "PMC Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Orders Total",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Orders Total],",
              "        PARALLELPERIOD ( 'D_Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "0a142971-3a12-4e68-b6bd-29725f3fe5f6"
          },
          {
            "name": "MTDOPM Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Orders Total",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD Orders Total]",
              "VAR __ValuePreviousPeriod = [PMC Orders Total]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "3218b825-3924-47df-b15b-f01cd073cdc4"
          },
          {
            "name": "MTDOPM % Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Orders Total",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM Orders Total],",
              "    [PMC Orders Total]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "1e5573a3-1415-42b2-b4b8-39ab5fabbea3"
          },
          {
            "name": "MAT Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Orders Total",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Orders Total],",
              "        DATESINPERIOD (",
              "            'D_Date'[Date],",
              "            MAX ( 'D_Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c1d6b667-3da2-4fc1-bfec-6338660bed6f"
          },
          {
            "name": "PYMAT Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Orders Total",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT Orders Total],",
              "        DATEADD ( 'D_Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "bf34e9e4-52bd-44d2-bf10-4ea40a727129"
          },
          {
            "name": "MATG Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Orders Total",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT Orders Total]",
              "VAR __ValuePreviousPeriod = [PYMAT Orders Total]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "a5977c74-ef0b-4e91-80d7-51cf52471bb9"
          },
          {
            "name": "MATG % Orders Total",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Orders Total",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG Orders Total],",
              "    [PYMAT Orders Total]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "f50be09e-24f5-47a2-b5d9-0d04cc58bf2b"
          },
          {
            "name": "YTD Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Total Sales",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Total Sales],",
              "        DATESYTD ( 'D_Date'[Date] )",
              "    )",
              ")"
            ],
            "lineageTag": "4917b66c-0b7a-4209-a630-505ab8377cbe"
          },
          {
            "name": "QTD Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Total Sales",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Total Sales],",
              "        DATESQTD ( 'D_Date'[Date] )",
              "    )",
              ")"
            ],
            "lineageTag": "7e602f64-496d-47e2-8d4a-10bce32ff3d9"
          },
          {
            "name": "MTD Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Total Sales",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Total Sales],",
              "        DATESMTD ( 'D_Date'[Date] )",
              "    )",
              ")"
            ],
            "lineageTag": "f2601fe9-a854-40d0-809d-3b49981238de"
          },
          {
            "name": "PY Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Total Sales",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Total Sales],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, YEAR ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "baf3d637-61da-4072-a5b9-01176a426b07"
          },
          {
            "name": "YOY Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Total Sales",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Total Sales]",
              "VAR __ValuePreviousPeriod = [PY Total Sales]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "b90f37c0-60e1-4d92-9319-235932856be7"
          },
          {
            "name": "YOY % Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Total Sales",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY Total Sales],",
              "    [PY Total Sales]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "20edd55f-44d1-4044-a4a6-8015bb42abc9"
          },
          {
            "name": "PQ Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Total Sales",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Total Sales],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, QUARTER ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "c6535c4d-e2b7-4207-9f7c-8264681a0602"
          },
          {
            "name": "QOQ Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Total Sales",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Total Sales]",
              "VAR __ValuePreviousPeriod = [PQ Total Sales]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "a3aebc4d-3b9d-4bb5-b6a7-c7da32576f05"
          },
          {
            "name": "QOQ % Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Total Sales",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ Total Sales],",
              "    [PQ Total Sales]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "44550a05-32a8-4456-82bf-d5b7387a1b05"
          },
          {
            "name": "PM Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Total Sales",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Total Sales],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, MONTH ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "5458d5ec-eeec-411d-81bd-4f413c479dc8"
          },
          {
            "name": "MOM Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Total Sales",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Total Sales]",
              "VAR __ValuePreviousPeriod = [PM Total Sales]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "1b04132e-401b-43f2-bd80-8a783ff6e196"
          },
          {
            "name": "MOM % Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Total Sales",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM Total Sales],",
              "    [PM Total Sales]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "7bd8f5eb-b467-4795-8593-d96e5efa8ec7"
          },
          {
            "name": "PYTD Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Total Sales",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD Total Sales],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, YEAR ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "d2d4a52b-de8b-4176-bf6f-318d8df4c822"
          },
          {
            "name": "YOYTD Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Total Sales",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD Total Sales]",
              "VAR __ValuePreviousPeriod = [PYTD Total Sales]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "9c7b949f-4b4e-4de9-ae77-0269f278b522"
          },
          {
            "name": "YOYTD % Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Total Sales",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD Total Sales],",
              "    [PYTD Total Sales]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "c2eaee32-1d7f-4f42-82a7-1a198a5ede6f"
          },
          {
            "name": "PQTD Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Total Sales",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD Total Sales],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, QUARTER ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "d1c1f194-a4b8-48bc-8da8-c5b1ad354858"
          },
          {
            "name": "QOQTD Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Total Sales",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD Total Sales]",
              "VAR __ValuePreviousPeriod = [PQTD Total Sales]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "8efa6eaf-7e06-40d0-9725-aec5bb7512ab"
          },
          {
            "name": "QOQTD % Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Total Sales",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD Total Sales],",
              "    [PQTD Total Sales]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "d393cf9c-885c-4023-8090-33e64c81ab59"
          },
          {
            "name": "PMTD Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Total Sales",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD Total Sales],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, MONTH ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "bd0b8911-097c-4421-9790-57b73716da78"
          },
          {
            "name": "MOMTD Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Total Sales",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD Total Sales]",
              "VAR __ValuePreviousPeriod = [PMTD Total Sales]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "5e13d1cc-01bb-4cba-b60b-3bba88e46c51"
          },
          {
            "name": "MOMTD % Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Total Sales",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD Total Sales],",
              "    [PMTD Total Sales]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "0517c80a-88db-4a99-9bf7-e5b83e77c52b"
          },
          {
            "name": "PYC Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Total Sales",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Total Sales],",
              "        PARALLELPERIOD ( 'D_Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "lineageTag": "b4a9ba80-9f62-40b2-b661-5c2400dfa6b6"
          },
          {
            "name": "YTDOPY Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Total Sales",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD Total Sales]",
              "VAR __ValuePreviousPeriod = [PYC Total Sales]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "3244e7e2-c7f7-4b06-a258-b9abf49cbd7f"
          },
          {
            "name": "YDTOPY % Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Total Sales",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY Total Sales],",
              "    [PYC Total Sales]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "3ecb5138-3e48-4240-9d6a-46daf617cf4b"
          },
          {
            "name": "PQC Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Total Sales",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Total Sales],",
              "        PARALLELPERIOD ( 'D_Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "lineageTag": "d4590021-01e9-4f45-87a0-7c0555165c20"
          },
          {
            "name": "QTDOPQ Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Total Sales",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD Total Sales]",
              "VAR __ValuePreviousPeriod = [PQC Total Sales]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "b31bbf87-be38-4c67-a25d-7f3d2350430a"
          },
          {
            "name": "QDTOPQ % Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Total Sales",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ Total Sales],",
              "    [PQC Total Sales]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "7217d936-632a-4726-8b79-071f444df4a8"
          },
          {
            "name": "PMC Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Total Sales",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Total Sales],",
              "        PARALLELPERIOD ( 'D_Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "lineageTag": "f66e4a7d-34e5-4e32-8336-9ca868679de7"
          },
          {
            "name": "MTDOPM Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Total Sales",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD Total Sales]",
              "VAR __ValuePreviousPeriod = [PMC Total Sales]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "10589891-802e-44e9-a78d-9df09694bd62"
          },
          {
            "name": "MTDOPM % Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Total Sales",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM Total Sales],",
              "    [PMC Total Sales]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "4a53e16e-0f27-4880-877b-47ea73df69eb"
          },
          {
            "name": "MAT Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Total Sales",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Total Sales],",
              "        DATESINPERIOD (",
              "            'D_Date'[Date],",
              "            MAX ( 'D_Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "fccdcc83-d689-4c10-943e-d8b5e581748d"
          },
          {
            "name": "PYMAT Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Total Sales",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT Total Sales],",
              "        DATEADD ( 'D_Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "lineageTag": "2ff9bd31-0cdc-4c91-9cd0-5591a93cd8bb"
          },
          {
            "name": "MATG Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Total Sales",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT Total Sales]",
              "VAR __ValuePreviousPeriod = [PYMAT Total Sales]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "6263678c-2eb2-41ac-8281-e0714b671acc"
          },
          {
            "name": "MATG % Total Sales",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Total Sales",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG Total Sales],",
              "    [PYMAT Total Sales]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "3aedc7c4-edf5-4a79-9c53-69287913ff68"
          },
          {
            "name": "YTD Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Products with low stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products with low stock],",
              "        DATESYTD ( 'D_Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1824bc6c-097b-40b5-9137-83d5a8e4de5c"
          },
          {
            "name": "QTD Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Products with low stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products with low stock],",
              "        DATESQTD ( 'D_Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b1b0deca-daca-4467-b3dc-75445e388727"
          },
          {
            "name": "MTD Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Products with low stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products with low stock],",
              "        DATESMTD ( 'D_Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "bec41d8c-0f5e-4b3f-8f78-671bc07c87b6"
          },
          {
            "name": "PY Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products with low stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products with low stock],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, YEAR ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "71e7c9f3-f283-4cb0-ae20-b8cd1f44fbbe"
          },
          {
            "name": "YOY Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products with low stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Products with low stock]",
              "VAR __ValuePreviousPeriod = [PY Products with low stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "4d77dd06-3e0e-4455-921f-624e4d04da12"
          },
          {
            "name": "YOY % Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products with low stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY Products with low stock],",
              "    [PY Products with low stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "0355bca0-66ce-44c8-9f00-98e3897f9780"
          },
          {
            "name": "PQ Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products with low stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products with low stock],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, QUARTER ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5f0c6686-40ab-49e2-976c-8674bbbdcc3d"
          },
          {
            "name": "QOQ Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products with low stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Products with low stock]",
              "VAR __ValuePreviousPeriod = [PQ Products with low stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "16d966f8-c8ec-4006-884e-7c9cba46f7cc"
          },
          {
            "name": "QOQ % Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products with low stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ Products with low stock],",
              "    [PQ Products with low stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "630de149-cf54-4c8c-b51b-ed5e8ab61dca"
          },
          {
            "name": "PM Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products with low stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products with low stock],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, MONTH ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "eeb9356d-2554-4fbc-9325-9ecb5783a3ac"
          },
          {
            "name": "MOM Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products with low stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Products with low stock]",
              "VAR __ValuePreviousPeriod = [PM Products with low stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "bd5f90b2-2c4f-45a3-9192-80c85bb0a3d8"
          },
          {
            "name": "MOM % Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products with low stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM Products with low stock],",
              "    [PM Products with low stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "5018ee80-7392-444f-9f4d-5e6e05c3b378"
          },
          {
            "name": "PYTD Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products with low stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD Products with low stock],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, YEAR ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "a0e15511-cb43-4fd1-be38-bd93d73ad54b"
          },
          {
            "name": "YOYTD Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products with low stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD Products with low stock]",
              "VAR __ValuePreviousPeriod = [PYTD Products with low stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "a0f61344-79a2-4f99-ba84-1883e45ce147"
          },
          {
            "name": "YOYTD % Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products with low stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD Products with low stock],",
              "    [PYTD Products with low stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "a3d7280d-bd51-49ae-a2e6-fcd75bb344b6"
          },
          {
            "name": "PQTD Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products with low stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD Products with low stock],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, QUARTER ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ed041546-1097-4efa-85b6-8df065508ae1"
          },
          {
            "name": "QOQTD Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products with low stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD Products with low stock]",
              "VAR __ValuePreviousPeriod = [PQTD Products with low stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "36c81541-c73a-442e-956c-3b6e9da4a62f"
          },
          {
            "name": "QOQTD % Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products with low stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD Products with low stock],",
              "    [PQTD Products with low stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "46a31881-4ff0-47e3-957a-410022a59b28"
          },
          {
            "name": "PMTD Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products with low stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD Products with low stock],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, MONTH ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "0474cb13-e0ca-4630-ab23-ca3a20af5b03"
          },
          {
            "name": "MOMTD Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products with low stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD Products with low stock]",
              "VAR __ValuePreviousPeriod = [PMTD Products with low stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "6ab29e38-82d5-4419-ba9b-bb8fe5754445"
          },
          {
            "name": "MOMTD % Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products with low stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD Products with low stock],",
              "    [PMTD Products with low stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "1c85cf56-a729-487e-ad2f-772f145e1d14"
          },
          {
            "name": "PYC Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products with low stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products with low stock],",
              "        PARALLELPERIOD ( 'D_Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "3f0c950a-ad5e-46f4-bf9b-3009c71eacf8"
          },
          {
            "name": "YTDOPY Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products with low stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD Products with low stock]",
              "VAR __ValuePreviousPeriod = [PYC Products with low stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "8700e21f-e8eb-455b-91fd-771325a69771"
          },
          {
            "name": "YDTOPY % Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products with low stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY Products with low stock],",
              "    [PYC Products with low stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "56587694-402c-4421-af20-83e3adec8793"
          },
          {
            "name": "PQC Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products with low stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products with low stock],",
              "        PARALLELPERIOD ( 'D_Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "2ac23c82-8faf-4f86-8970-b31077ddc12a"
          },
          {
            "name": "QTDOPQ Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products with low stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD Products with low stock]",
              "VAR __ValuePreviousPeriod = [PQC Products with low stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "7ad1276d-e1fa-4af1-928d-4fc20175ef8e"
          },
          {
            "name": "QDTOPQ % Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products with low stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ Products with low stock],",
              "    [PQC Products with low stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "c01e4b65-10db-4bd3-88bf-a178e1fa1f9f"
          },
          {
            "name": "PMC Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products with low stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products with low stock],",
              "        PARALLELPERIOD ( 'D_Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ccec3f16-a9ad-410a-843a-a19e642086a0"
          },
          {
            "name": "MTDOPM Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products with low stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD Products with low stock]",
              "VAR __ValuePreviousPeriod = [PMC Products with low stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "dba5d83c-1897-4e9d-8a51-022e4d60c21e"
          },
          {
            "name": "MTDOPM % Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products with low stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM Products with low stock],",
              "    [PMC Products with low stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "c23998c5-55b9-495d-9a7a-b9f97e4d3ad0"
          },
          {
            "name": "MAT Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Products with low stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products with low stock],",
              "        DATESINPERIOD (",
              "            'D_Date'[Date],",
              "            MAX ( 'D_Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "3b2c55b1-5d66-4661-aa7c-6f06c4a2075d"
          },
          {
            "name": "PYMAT Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Products with low stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT Products with low stock],",
              "        DATEADD ( 'D_Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "22e19af0-ee7d-4063-89b2-1d52311078f7"
          },
          {
            "name": "MATG Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Products with low stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT Products with low stock]",
              "VAR __ValuePreviousPeriod = [PYMAT Products with low stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "c69db3f6-bc3f-45c4-a1e0-eb1b62783e20"
          },
          {
            "name": "MATG % Products with low stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Products with low stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG Products with low stock],",
              "    [PYMAT Products with low stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "40e6b8ef-ccff-4947-933b-5b4ba40ad603"
          },
          {
            "name": "YTD Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Products high on stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products high on stock],",
              "        DATESYTD ( 'D_Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ff31cbf5-a8f3-49b8-8908-d0716fc13852"
          },
          {
            "name": "QTD Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Products high on stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products high on stock],",
              "        DATESQTD ( 'D_Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "e15b05f8-e4b1-423d-89c5-380d046a183a"
          },
          {
            "name": "MTD Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Products high on stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products high on stock],",
              "        DATESMTD ( 'D_Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "d12c2ef4-8f1f-45ce-ad7b-086465471543"
          },
          {
            "name": "PY Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products high on stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products high on stock],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, YEAR ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "127d8632-e37c-4c8d-9d89-aaa7304338d9"
          },
          {
            "name": "YOY Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products high on stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Products high on stock]",
              "VAR __ValuePreviousPeriod = [PY Products high on stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "28cb7d3c-e2a4-49f0-aa44-c44fc77840e6"
          },
          {
            "name": "YOY % Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products high on stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY Products high on stock],",
              "    [PY Products high on stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "79cba0f7-8603-4fc9-9c84-688e1f76568d"
          },
          {
            "name": "PQ Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products high on stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products high on stock],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, QUARTER ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f26d28be-eb4b-4165-9fb4-40391c613862"
          },
          {
            "name": "QOQ Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products high on stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Products high on stock]",
              "VAR __ValuePreviousPeriod = [PQ Products high on stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "345631e8-60de-4280-9b1b-3c972ac219cb"
          },
          {
            "name": "QOQ % Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products high on stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ Products high on stock],",
              "    [PQ Products high on stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "e19f956c-4a46-48b5-bb4c-0fdcc45cc978"
          },
          {
            "name": "PM Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products high on stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products high on stock],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, MONTH ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "8f3721e7-1c6e-4e97-9d2a-ea72c06a23e5"
          },
          {
            "name": "MOM Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products high on stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Products high on stock]",
              "VAR __ValuePreviousPeriod = [PM Products high on stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "0b5f67ee-6339-4446-8d19-8c7f6d7e84e8"
          },
          {
            "name": "MOM % Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Products high on stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM Products high on stock],",
              "    [PM Products high on stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "11d70af9-42df-4a9d-a841-5102e94dac9c"
          },
          {
            "name": "PYTD Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products high on stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD Products high on stock],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, YEAR ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "511be8f5-825d-46c5-bd7a-d4bec80db82b"
          },
          {
            "name": "YOYTD Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products high on stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD Products high on stock]",
              "VAR __ValuePreviousPeriod = [PYTD Products high on stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "52e776be-f1a2-4a37-b353-bc5e58c64503"
          },
          {
            "name": "YOYTD % Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products high on stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD Products high on stock],",
              "    [PYTD Products high on stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "ef325335-b16b-40a5-9467-273c3c4c21ee"
          },
          {
            "name": "PQTD Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products high on stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD Products high on stock],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, QUARTER ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "7b855e87-b358-4a45-ac87-67372781d31e"
          },
          {
            "name": "QOQTD Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products high on stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD Products high on stock]",
              "VAR __ValuePreviousPeriod = [PQTD Products high on stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "c63b7f1c-be8c-42b6-b348-d0f1e2aa3bc1"
          },
          {
            "name": "QOQTD % Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products high on stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD Products high on stock],",
              "    [PQTD Products high on stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "94583916-89db-4682-aa22-b7b10e6caa4b"
          },
          {
            "name": "PMTD Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products high on stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD Products high on stock],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, MONTH ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c9a97dd2-9aa2-4dea-a179-77c2261305ee"
          },
          {
            "name": "MOMTD Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products high on stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD Products high on stock]",
              "VAR __ValuePreviousPeriod = [PMTD Products high on stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "cac9fb17-ae9c-4a16-8ec7-12a3b2f73fb5"
          },
          {
            "name": "MOMTD % Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Products high on stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD Products high on stock],",
              "    [PMTD Products high on stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "f4c1b2d0-da88-472b-886e-82726c01f1fe"
          },
          {
            "name": "PYC Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products high on stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products high on stock],",
              "        PARALLELPERIOD ( 'D_Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "d747b029-c5db-432d-a552-d28192c47579"
          },
          {
            "name": "YTDOPY Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products high on stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD Products high on stock]",
              "VAR __ValuePreviousPeriod = [PYC Products high on stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "62b9e83e-07b3-4583-ad4e-ef2bf4c1c701"
          },
          {
            "name": "YDTOPY % Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products high on stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY Products high on stock],",
              "    [PYC Products high on stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "760b0642-7012-4b76-a2f9-a8ae123632e5"
          },
          {
            "name": "PQC Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products high on stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products high on stock],",
              "        PARALLELPERIOD ( 'D_Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "9301b1bf-bfe1-4c87-8d81-3a2567c7447e"
          },
          {
            "name": "QTDOPQ Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products high on stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD Products high on stock]",
              "VAR __ValuePreviousPeriod = [PQC Products high on stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "d6e2e3ea-3f13-403a-8706-37a9e648ad46"
          },
          {
            "name": "QDTOPQ % Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products high on stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ Products high on stock],",
              "    [PQC Products high on stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "ba19714e-1c36-415b-b01a-f11d147644d0"
          },
          {
            "name": "PMC Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products high on stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products high on stock],",
              "        PARALLELPERIOD ( 'D_Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f3091a48-7cf3-4442-9072-04e8730e6c6c"
          },
          {
            "name": "MTDOPM Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products high on stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD Products high on stock]",
              "VAR __ValuePreviousPeriod = [PMC Products high on stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "53e91b76-ad70-4012-af79-ef5a2471a404"
          },
          {
            "name": "MTDOPM % Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Products high on stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM Products high on stock],",
              "    [PMC Products high on stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "137206a4-017a-4477-bf09-0d9c9a182bf3"
          },
          {
            "name": "MAT Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Products high on stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Products high on stock],",
              "        DATESINPERIOD (",
              "            'D_Date'[Date],",
              "            MAX ( 'D_Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "34be60c4-8528-4343-ae99-83ea8dd5ae06"
          },
          {
            "name": "PYMAT Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Products high on stock",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT Products high on stock],",
              "        DATEADD ( 'D_Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c76c137e-37cf-43f7-8683-c18506c0c555"
          },
          {
            "name": "MATG Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Products high on stock",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT Products high on stock]",
              "VAR __ValuePreviousPeriod = [PYMAT Products high on stock]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "f827c2eb-f65a-436b-b635-1c5cb2895166"
          },
          {
            "name": "MATG % Products high on stock",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Products high on stock",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG Products high on stock],",
              "    [PYMAT Products high on stock]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "a7de14a5-46cd-4906-8a61-f0267723c3cf"
          },
          {
            "name": "Sales per order",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Total Sales]/[Orders Total]",
            "lineageTag": "59b8ac92-11f4-4d5c-a352-14f793fc41db"
          },
          {
            "name": "YTD Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Sales per order",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Sales per order],",
              "        DATESYTD ( 'D_Date'[Date] )",
              "    )",
              ")"
            ],
            "lineageTag": "cc78fa04-8a27-4202-b764-27c930757d44"
          },
          {
            "name": "QTD Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Sales per order",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Sales per order],",
              "        DATESQTD ( 'D_Date'[Date] )",
              "    )",
              ")"
            ],
            "lineageTag": "7c543932-ac43-4311-ac17-450c640dd03e"
          },
          {
            "name": "MTD Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Sales per order",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Sales per order],",
              "        DATESMTD ( 'D_Date'[Date] )",
              "    )",
              ")"
            ],
            "lineageTag": "33c63cf0-5c15-49cc-9b5d-147eb688a620"
          },
          {
            "name": "PY Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Sales per order",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Sales per order],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, YEAR ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "0ec811ad-ac95-4395-bd72-15732c0103d7"
          },
          {
            "name": "YOY Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Sales per order",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Sales per order]",
              "VAR __ValuePreviousPeriod = [PY Sales per order]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "7125ba6b-71b9-402e-893b-45024b9191e7"
          },
          {
            "name": "YOY % Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Sales per order",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY Sales per order],",
              "    [PY Sales per order]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "27b4646e-70bd-41af-b993-11c50e897285"
          },
          {
            "name": "PQ Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Sales per order",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Sales per order],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, QUARTER ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "91ed738d-87b9-4309-a75c-ebc5f729e742"
          },
          {
            "name": "QOQ Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Sales per order",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Sales per order]",
              "VAR __ValuePreviousPeriod = [PQ Sales per order]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "67bd5a65-2c8c-4aef-98c8-66c83744d789"
          },
          {
            "name": "QOQ % Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Sales per order",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ Sales per order],",
              "    [PQ Sales per order]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "bee59859-337d-42a0-8026-0e607bcf3a03"
          },
          {
            "name": "PM Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Sales per order",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Sales per order],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, MONTH ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "9b68e538-a5cc-4baa-b24e-b0cbc65f1739"
          },
          {
            "name": "MOM Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Sales per order",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Sales per order]",
              "VAR __ValuePreviousPeriod = [PM Sales per order]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "7945c92b-c5b9-448a-949b-3189df8e38e0"
          },
          {
            "name": "MOM % Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Sales per order",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM Sales per order],",
              "    [PM Sales per order]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "5e4e6bae-76e4-4f17-8e90-fc6f75b07a6c"
          },
          {
            "name": "PYTD Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Sales per order",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD Sales per order],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, YEAR ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "4bf832e2-38e7-4cf6-8eed-a3b3872d1519"
          },
          {
            "name": "YOYTD Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Sales per order",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD Sales per order]",
              "VAR __ValuePreviousPeriod = [PYTD Sales per order]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "007e3357-caed-4e04-a35d-2778f7f1877a"
          },
          {
            "name": "YOYTD % Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Sales per order",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD Sales per order],",
              "    [PYTD Sales per order]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "b7d1e90d-5793-4707-aca9-4f1bfaa97de4"
          },
          {
            "name": "PQTD Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Sales per order",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD Sales per order],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, QUARTER ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "c9d3d7a3-e4c2-4c58-83e5-28dbe5a1d1b5"
          },
          {
            "name": "QOQTD Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Sales per order",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD Sales per order]",
              "VAR __ValuePreviousPeriod = [PQTD Sales per order]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "9997d305-5013-4342-84cd-1ce4fa2529e3"
          },
          {
            "name": "QOQTD % Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Sales per order",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD Sales per order],",
              "    [PQTD Sales per order]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "c2707f95-d626-421a-af30-1448eb81aff3"
          },
          {
            "name": "PMTD Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Sales per order",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD Sales per order],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'D_Date'[Date], -1, MONTH ),",
              "            'D_Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "8c0d61da-f08e-44a4-a947-b30dd0f9c216"
          },
          {
            "name": "MOMTD Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Sales per order",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD Sales per order]",
              "VAR __ValuePreviousPeriod = [PMTD Sales per order]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "73e743b3-9180-447f-9f48-21cd9cf04a11"
          },
          {
            "name": "MOMTD % Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Sales per order",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD Sales per order],",
              "    [PMTD Sales per order]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "ac812ae1-a41f-4d16-81c1-a3074bee1f21"
          },
          {
            "name": "PYC Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Sales per order",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Sales per order],",
              "        PARALLELPERIOD ( 'D_Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "lineageTag": "860d51d4-da70-4f99-b7c1-8ea345f3e27d"
          },
          {
            "name": "YTDOPY Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Sales per order",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD Sales per order]",
              "VAR __ValuePreviousPeriod = [PYC Sales per order]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "c2b61a5e-5592-4533-8145-e9e2aef1ea72"
          },
          {
            "name": "YDTOPY % Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Sales per order",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY Sales per order],",
              "    [PYC Sales per order]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "aa7e1a71-2778-473e-a7f6-5e54bd91cc1b"
          },
          {
            "name": "PQC Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Sales per order",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Sales per order],",
              "        PARALLELPERIOD ( 'D_Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "lineageTag": "d9c8836c-9ec0-4f5c-8d7f-9853e5a832fa"
          },
          {
            "name": "QTDOPQ Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Sales per order",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD Sales per order]",
              "VAR __ValuePreviousPeriod = [PQC Sales per order]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "963fc325-04f4-4c71-bc57-3f4e70183793"
          },
          {
            "name": "QDTOPQ % Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Sales per order",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ Sales per order],",
              "    [PQC Sales per order]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "6bf18a2b-3693-4807-add3-5fd923b8a265"
          },
          {
            "name": "PMC Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Sales per order",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Sales per order],",
              "        PARALLELPERIOD ( 'D_Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "lineageTag": "952a4636-bff4-4f91-993e-33116992bcb3"
          },
          {
            "name": "MTDOPM Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Sales per order",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD Sales per order]",
              "VAR __ValuePreviousPeriod = [PMC Sales per order]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "5be30378-7a19-4b2a-8c7e-a7f24d0a2618"
          },
          {
            "name": "MTDOPM % Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Sales per order",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM Sales per order],",
              "    [PMC Sales per order]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "2d853aff-d652-467c-ba12-22d542436471"
          },
          {
            "name": "MAT Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Sales per order",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Sales per order],",
              "        DATESINPERIOD (",
              "            'D_Date'[Date],",
              "            MAX ( 'D_Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "450c228e-19d2-4504-968a-12fe3f8ea62d"
          },
          {
            "name": "PYMAT Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Sales per order",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT Sales per order],",
              "        DATEADD ( 'D_Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "lineageTag": "61982093-12b3-4484-bb2c-7036a6d07595"
          },
          {
            "name": "MATG Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Sales per order",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT Sales per order]",
              "VAR __ValuePreviousPeriod = [PYMAT Sales per order]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "f9afab99-9c60-4602-acbe-beb599281d38"
          },
          {
            "name": "MATG % Sales per order",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Sales per order",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG Sales per order],",
              "    [PYMAT Sales per order]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "ef983aff-745a-4e20-8851-10223b54149a"
          }
        ],
        "partitions": [
          {
            "name": "Mittarit",
            "mode": "import",
            "source": {
              "expression": "ADDCOLUMNS()",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DateAutoTemplate",
        "annotations": [
          {
            "name": "SQLBI_Template",
            "value": "Dates"
          },
          {
            "name": "SQLBI_TemplateTable",
            "value": "DateAutoTemplate"
          },
          {
            "name": "SQLBI_CalendarType",
            "value": "Calendar"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "Date"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "m/d/yyyy",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "55e532a5-fde6-4377-af4e-78639c8908b2",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "dataCategory": "Years",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ca1c0bd0-7980-466f-af34-049f35005231",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Quarter Number",
            "dataCategory": "Quarters",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "140ee989-1a02-4029-bee5-4d39fa231386",
            "sourceColumn": "[Year Quarter Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Quarter",
            "dataCategory": "Quarters",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "072e3da4-4cae-4eda-a986-362dc826b2f8",
            "sortByColumn": "Year Quarter Number",
            "sourceColumn": "[Year Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "dataCategory": "QuarterOfYear",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7f8d28f1-23fd-4b61-a391-58bc38712da3",
            "sourceColumn": "[Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month",
            "dataCategory": "Months",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cefb8f2f-6215-4966-a4b5-b51298260b31",
            "sortByColumn": "Year Month Number",
            "sourceColumn": "[Year Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month Number",
            "dataCategory": "Months",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "db4e0175-f29e-4c0e-80fa-aa4d46532052",
            "sourceColumn": "[Year Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "dataCategory": "MonthOfYear",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c7899258-61ff-4607-879a-d1e07bd027be",
            "sortByColumn": "Month Number",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Number",
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d8ae2485-f34f-4192-a9c5-90ba6888f07c",
            "sourceColumn": "[Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DayOfWeek"
              },
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ],
            "dataCategory": "DayOfWeek",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d0c04db5-8aa7-40ee-be58-7e2c716c747b",
            "sourceColumn": "[Day of Week Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ],
            "dataCategory": "DayOfWeek",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d8c93dc8-b149-462a-bbf8-926b17cd1793",
            "sortByColumn": "Day of Week Number",
            "sourceColumn": "[Day of Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DateWithTransactions",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DateDuration"
              }
            ],
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d1c8e1fc-c7c1-4342-8afb-6f0a6ac44994",
            "sourceColumn": "[DateWithTransactions]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Calendar",
            "isHidden": true,
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b62b45cc-d413-48f0-b614-118fa8bb397b",
                "ordinal": 0
              },
              {
                "name": "Month",
                "column": "Year Month",
                "lineageTag": "ad83e44f-ab53-4bdf-b3c8-577dbe89fbe4",
                "ordinal": 1
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "1fd67ca4-5bf5-410a-ba87-69c559e45c7a",
                "ordinal": 2
              }
            ],
            "lineageTag": "7204aef2-9adc-4551-b5e6-7bb30970c632"
          }
        ],
        "isHidden": true,
        "lineageTag": "b81db05b-9972-4c2a-8f3d-9d787c1ab3cc",
        "partitions": [
          {
            "name": "DateAutoTemplate",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "--  ",
                "--     Configuration",
                "--  ",
                "VAR __FirstDayOfWeek = 1",
                "----------------------------------------",
                "VAR __WeekDayCalculationType = IF ( __FirstDayOfWeek = 0, 7, __FirstDayOfWeek ) + 10",
                "VAR __Calendar = ",
                "    VAR __FirstYear = YEAR ( MINX ( { MIN ( 'F_OrderData'[order_date] ), MIN ( 'F_OrderData'[delivery_date] ), MIN ( 'F_OrderData'[shipped_date] ) }, ''[Value] ) )",
                "    VAR __LastYear =  YEAR ( MAXX ( { MAX ( 'F_OrderData'[order_date] ), MAX ( 'F_OrderData'[delivery_date] ), MAX ( 'F_OrderData'[shipped_date] ) }, ''[Value] ) )",
                "    RETURN CALENDAR (",
                "        DATE ( __FirstYear, 1, 1 ),",
                "        DATE ( __LastYear, 12, 31 )",
                "    )",
                "VAR __Step3 = ",
                "    GENERATE (",
                "        __Calendar,",
                "        VAR __IsStandardLocale = IF ( FORMAT( DATE( 2000, 1, 1 ), \"oooo\" ) = \"oooo\", TRUE, FALSE )",
                "        VAR __MonthFormatString = IF( __IsStandardLocale, \"mmm\", \"ooo\" )",
                "        VAR __DayFormatString = IF( __IsStandardLocale, \"ddd\", \"aaa\" )",
                "        VAR __LastTransactionDate = MAXX ( { MAX ( 'F_OrderData'[order_date] ), MAX ( 'F_OrderData'[delivery_date] ), MAX ( 'F_OrderData'[shipped_date] ) }, ''[Value] )",
                "        VAR __Date = [Date]",
                "        VAR __YearNumber = YEAR ( __Date )",
                "        VAR __QuarterNumber = QUARTER ( __Date )",
                "        VAR __YearQuarterNumber = CONVERT ( __YearNumber * 4 + __QuarterNumber - 1, INTEGER )",
                "        VAR __MonthNumber = MONTH ( __Date )",
                "        VAR __WeekDayNumber = WEEKDAY ( __Date, __WeekDayCalculationType )",
                "        VAR __WeekDay = FORMAT ( __Date, __DayFormatString )",
                "        RETURN ROW ( ",
                "            \"Year\", __YearNumber,",
                "            \"Year Quarter Number\", __YearQuarterNumber,",
                "            \"Year Quarter\", FORMAT ( __QuarterNumber, \"\\Q0\" ) & \"-\" & FORMAT ( __YearNumber, \"0000\" ),",
                "            \"Quarter\", FORMAT( __QuarterNumber, \"\\Q0\" ),",
                "            \"Year Month\", FORMAT ( __Date, __MonthFormatString & \" yyyy\" ),",
                "            \"Year Month Number\", __YearNumber * 12 + __MonthNumber - 1,",
                "            \"Month\", FORMAT ( __Date, __MonthFormatString ),",
                "            \"Month Number\", __MonthNumber,",
                "            \"Day of Week Number\", __WeekDayNumber,",
                "            \"Day of Week\", __WeekDay,",
                "            \"DateWithTransactions\", __Date <= __LastTransactionDate ",
                "        )",
                "    )",
                "RETURN",
                "    __Step3"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "D_Date",
        "annotations": [
          {
            "name": "SQLBI_Template",
            "value": "Dates"
          },
          {
            "name": "SQLBI_TemplateTable",
            "value": "Date"
          },
          {
            "name": "SQLBI_CalendarType",
            "value": "Calendar"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "Date"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "m/d/yyyy",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "0e62c2e6-3481-4345-b8e6-07365cb2f4a3",
            "sourceColumn": "DateAutoTemplate[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b1d0ab51-21e5-48a1-9b6f-d06596bb1c55",
            "sourceColumn": "DateAutoTemplate[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1dabcf86-d9cc-4cf5-8bf2-394c9965839b",
            "sourceColumn": "DateAutoTemplate[Year Quarter Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Quarter",
            "dataCategory": "Quarters",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c301ca03-c510-4b11-bdd3-36aee1aa1ad7",
            "sortByColumn": "Year Quarter Number",
            "sourceColumn": "DateAutoTemplate[Year Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "dataCategory": "QuarterOfYear",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "646e01c6-4cb4-4db7-81f8-b06ecb6c2d18",
            "sourceColumn": "DateAutoTemplate[Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month",
            "dataCategory": "Months",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "585ff088-7a6e-4335-97ae-2d4a874bad59",
            "sortByColumn": "Year Month Number",
            "sourceColumn": "DateAutoTemplate[Year Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Months",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "05af759b-24a0-45a3-9435-0346f923625f",
            "sourceColumn": "DateAutoTemplate[Year Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "dataCategory": "MonthOfYear",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0434eb6f-2890-4183-a020-5ef5b4e083df",
            "sortByColumn": "Month Number",
            "sourceColumn": "DateAutoTemplate[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a6a748bf-ed4b-4f5a-b6f1-ce2d6771f2de",
            "sourceColumn": "DateAutoTemplate[Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DayOfWeek"
              },
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "DayOfWeek",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "746856ed-2b85-4a0b-884b-bf80f0872b56",
            "sourceColumn": "DateAutoTemplate[Day of Week Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ],
            "dataCategory": "DayOfWeek",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "714018c2-5fc6-4e39-ac27-f2215c5e1211",
            "sortByColumn": "Day of Week Number",
            "sourceColumn": "DateAutoTemplate[Day of Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DateWithTransactions",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DateDuration"
              }
            ],
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "79400407-45ef-4f7c-844d-9249a890a06a",
            "sourceColumn": "DateAutoTemplate[DateWithTransactions]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Calendar",
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "510825d8-7b1c-47ca-98d5-259f248c61e4",
                "ordinal": 0
              },
              {
                "name": "Month",
                "column": "Year Month",
                "lineageTag": "cf9c2dad-8c43-4c21-990a-b22a285a4d2d",
                "ordinal": 1
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "d42988c6-2eec-4670-9c8e-a1a526051962",
                "ordinal": 2
              }
            ],
            "lineageTag": "d2c08c9b-7c24-440d-b6a9-d272b841cef5"
          }
        ],
        "lineageTag": "83b3b6f5-8a99-4bb0-8527-4d753bfa24c9",
        "measures": [
          {
            "name": "_ShowValueForDates",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Hidden Time Intelligence",
            "expression": [
              "",
              "VAR __LastDateWithData =",
              "    CALCULATE (",
              "        MAXX ( { MAX ( 'F_OrderData'[order_date] ), MAX ( 'F_OrderData'[delivery_date] ), MAX ( 'F_OrderData'[shipped_date] ) }, ''[Value] ),",
              "        REMOVEFILTERS ()",
              "    )",
              "VAR __FirstDateVisible =",
              "    MIN ( 'D_Date'[Date] )",
              "VAR __Result =",
              "    __FirstDateVisible <= __LastDateWithData",
              "RETURN",
              "    __Result"
            ],
            "isHidden": true,
            "lineageTag": "b8b984aa-5bf8-47be-8107-fe7d6012c5e1"
          }
        ],
        "partitions": [
          {
            "name": "D_Date",
            "mode": "import",
            "source": {
              "expression": "DateAutoTemplate",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "F_OrderData",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "order_item_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e2ee1653-8064-4995-943e-798b5e6e6839",
            "sourceColumn": "order_item_id",
            "summarizeBy": "sum"
          },
          {
            "name": "order_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6633a249-587d-4323-b42d-c51d161b95c9",
            "sourceColumn": "order_id",
            "summarizeBy": "sum"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "684a3913-9676-4b2c-84ca-dabf32c1aa71",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ba67b7ac-35ff-456e-a592-89f2b3940b8d",
            "sourceColumn": "quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "price_at_purchase",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8d15dfd8-1aa9-4d62-9b75-92c8a3d08ac2",
            "sourceColumn": "price_at_purchase",
            "summarizeBy": "sum"
          },
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "67bd2a01-0ef9-426c-8f4d-4e3384597d9f",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "order_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a0b19732-fbfd-44d9-9549-6c2e36169706",
            "sourceColumn": "order_date",
            "summarizeBy": "none"
          },
          {
            "name": "order_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ae23375-85b3-463a-a736-87da045c6fb4",
            "sourceColumn": "order_status",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4bdf02ea-b90c-4ca6-b612-803381dda95c",
            "sourceColumn": "supplier_id",
            "summarizeBy": "none"
          },
          {
            "name": "delivery_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f54271a5-0dcc-417d-98f1-fea711ca918e",
            "sourceColumn": "delivery_date",
            "summarizeBy": "none"
          },
          {
            "name": "shipment_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7fd1daa2-c40a-475b-a1d6-891efc2f082d",
            "sourceColumn": "shipment_id",
            "summarizeBy": "sum"
          },
          {
            "name": "shipped_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8a2e2cfa-1199-4c47-a044-60baea01c41d",
            "sourceColumn": "shipped_date",
            "summarizeBy": "none"
          },
          {
            "name": "shipping_cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5b770967-b600-4173-8f29-368f2c6e0265",
            "sourceColumn": "shipping_cost",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d319e422-4cec-40bb-838a-95f33eaf594a",
        "partitions": [
          {
            "name": "F_OrderData",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.NestedJoin(F_Order_Items, {\"order_id\"}, D_Orders, {\"order_id\"}, \"D_Orders\", JoinKind.LeftOuter),",
                "    #\"Expanded D_Orders\" = Table.ExpandTableColumn(Source, \"D_Orders\", {\"customer_id\", \"delivery_date\", \"order_date\", \"order_status\", \"shipment_id\", \"shipped_date\", \"shipping_cost\"}, {\"customer_id\", \"delivery_date\", \"order_date\", \"order_status\", \"shipment_id\", \"shipped_date\", \"shipping_cost\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Expanded D_Orders\", {\"product_id\"}, D_Products, {\"product_id\"}, \"D_Products\", JoinKind.LeftOuter),",
                "    #\"Expanded D_Products\" = Table.ExpandTableColumn(#\"Merged Queries\", \"D_Products\", {\"supplier_id\"}, {\"supplier_id\"})",
                "in",
                "    #\"Expanded D_Products\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}